stages:
    - test
    - publish

include:
    - project: "ci/common-ci"
      ref: master
      file: "sonarqube/sonarqube.gitlab-ci.yml"
    - project: "ci/common-ci"
      ref: master
      file: "npm/publish-npm.gitlab-ci.yml"